version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/" # Root of your Laravel project
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "security"
    open-pull-requests-limit: 5
    rebase-strategy: auto
